server:
  port: 10200

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx-cloud-order?characterEncoding=UTF8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: SZ
    # openfeign日志级别配置
    openfeign:
      client:
        config:
          spzx-cloud-user:  # default: 为所有模块配置日志级别
            loggerLevel: full
            read-timeout: 2000           # 读取数据的超时时间设置为2s
            connect-timeout: 2000        # 建立连接的超时时间设置为2s
            retryer: com.atqingke.spzx.cloud.feign.config.FeignClientRetryer		# 配置自定义重试器
    sentinel:
      transport:
        dashboard: localhost:8858
      datasource:
        ds1:
          nacos:
            serverAddr: localhost:8848
            dataId: sentinel-rules
            groupId: DEFAULT_GROUP
            dataType: json
            ruleType: flow
  # nacos config
  #     [
  #         {
  #              "resource": "/testA",
  #              "limitApp": "default",
  #              "grade": 1,
  #              "count": 1,
  #              "strategy": 0,
  #              "controlBehavior": 0,
  #              "clusterMode": false
  #         }
  #     ]
  application:
    name: spzx-cloud-order

# 将feign包下产生的日志的级别设置为debug
logging:
  level:
    com.atqingke.spzx.cloud.order.feign: debug
# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.atqingke.spzx.cloud.model.entity.order
  mapper-locations: classpath:/mapper/*.xml
feign:
  sentinel:
    enabled: true