version: '3'
services:
  redis-master:
    image: redis7.2-6379
    container_name: redis-master
    ports:
      - "6379:6379"
  redis-slave1:
    image: redis7.2-6380
    container_name: redis-slave1
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
  redis-slave2:
    image: redis7.2-6381
    container_name: redis-slave2
    ports:
      - "6381:6379"
    depends_on:
      - redis-master