server:
  port: 10100

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx-cloud-user?characterEncoding=UTF8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: SZ
        weight: 0.1
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
  #  config:
#    import:
#      - nacos:spzx-cloud-user-dev.yml
  application:
    name: spzx-cloud-user

# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.atqingke.spzx.cloud.model.entity.user
  mapper-locations: classpath:/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"    # 开启所有需要监控的指标端点
  endpoint:
    health:
      show-details: always