version: '3.1'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3309:3306'
    volumes:
      - mysql_user_system_data:/var/lib/mysql

volumes:
  mysql_user_system_data:
