version: '3'

services:
  server-user:
    image: mysql:latest
    container_name: server-user
    restart: always
    ports:
      - "3315:3306"
    volumes:
      - /docker/mysql/server/user:/var/lib/mysql
      - ./tt-docker-compose/VerticalSharding/server-user.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  server-order:
    image: mysql:latest
    container_name: server-order
    restart: always
    ports:
      - "3316:3306"
    volumes:
      - /docker/mysql/server/order:/var/lib/mysql
      - ./tt-docker-compose/VerticalSharding/server-order.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
